
spring:
  jpa:
    hibernate:
      ddlAuto: update

  datasource:
    url: jdbc:mysql://localhost:3306/book_store
    username: root
    password: 1312acab
    driverClassName: com.mysql.cj.jdbc.Driver

