
spring:
  jpa:
    hibernate:
      ddlAuto: update

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver

